name: Estrai Eventi Fuorisalone

on:
  schedule:
    - cron: '0 3 * * *' # Si avvia ogni notte alle 03:00 (Orario Server)
  workflow_dispatch: # Questo ci permette di avviarlo manualmente con un bottone!

jobs:
  aggiorna-dati:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permette a GitHub di salvare i file creati

    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4

      - name: Prepara Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa le librerie
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Lancia lo Scraper
        run: python scraper.py

      - name: Salva il JSON aggiornato nel repository
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'action@github.com'
          git add eventi_design_week_2026.json
          git commit -m "Aggiornamento automatico eventi" || echo "Nessun nuovo evento"
          git push
